name: Train Model CI

on:
  workflow_dispatch:
  push:
    paths:
      - MLProject/**

permissions:
  contents: write  

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install MLflow
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run MLProject -P data_path=dataset_preprocessing.zip

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/

  commit-artifact:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: trained-model

      - name: Commit artifact to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trained-model/
          git commit -m "chore: add trained model artifact [auto]" || echo "Nothing to commit"
          git push origin main
