name: Train Model CI

on:
  workflow_dispatch:
  push:
    paths:
      - MLProject/**
permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: Install additional pip dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow dagshub

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run MLProject -P data_path=dataset_preprocessing.zip

      - name: Salin model ke folder repo
        shell: bash -l {0}
        run: |
          mkdir -p trained_model
          cp -r MLProject/mlruns trained_model/

      - name: Commit model ke repo
        shell: bash -l {0}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add trained_model/
          git commit -m "chore: update trained model artifacts"
          git push
